services:
  db:
    ports:
      - "5432:5432"
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: max-explorer
      POSTGRES_USER: max-explorer
      POSTGRES_DB: max-explorer
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: