services:
  app:
    build:
      context: .
      target: deps
    container_name: max-explorer-app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://max-explorer:max-explorer@db:5432/max-explorer
      HOST: 0.0.0.0
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - db

  db:
    image: postgres:18
    container_name: max-explorer-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: max-explorer
      POSTGRES_USER: max-explorer
      POSTGRES_DB: max-explorer
    volumes:
      - postgres:/var/lib/postgresql/18/data

volumes:
  postgres:
