### GET request to example server
GET http://localhost:3000/api/train-v2?origin=Paris&departureDate=2024-11-04&returnDate=2024-11-05

###

### Import Train Data From SNCF API to Database
POST http://localhost:3000/api/import-trains

###

### Get Destination Coordinates
GET http://localhost:3000/api/get-destination-coordinates?destinationName=Uzes

###