### GET request to example server
GET http://localhost:3000/api/train-v2?origin=Toulouse&departureDate=2024-11-04&returnDate=2024-11-05

###

### GET With Destination
GET http://localhost:3000/api/train-v2?origin=Toulouse&destination=Nimes&departureDate=2024-11-04&returnDate=2024-11-05

###


### POST Import Train from SNCF API
POST http://localhost:3000/api/import-trains


## Paris -> Toulouse
## Paris -> Limoge
## Paris -> Birve

## Limoge -> Toulouse