# This is a basic workflow to help you get started with Actions

name: Test and Deploy on VPS

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '**'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Start services (Postgres)
        run: npm run docker:up

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          POSTGRES_CONTAINER=$(docker ps --filter "name=postgres_max-explorer" --format "{{.ID}}")
          for i in {1..20}; do
            if docker exec "$POSTGRES_CONTAINER" pg_isready -U postgres; then
              echo "PostgreSQL is ready!"
              break
            fi
            echo "Still waiting for PostgreSQL... ($i)"
            sleep 3
          done


      - name: Run tests
        run: npm run test
  build:
    runs-on: ubuntu-latest
    needs: test  # Le job build dépend maintenant du job test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: 📦 Deploy using SSH
        uses: appleboy/ssh-action@master
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          OPEN_WEATHER_MAP_API_KEY: ${{ secrets.OPEN_WEATHER_MAP_API_KEY }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          envs: DATABASE_URL,POSTGRES_USER,POSTGRES_PASSWORD,POSTGRES_DB,OPEN_WEATHER_MAP_API_KEY
          script: |
            echo "🚀 Starting deployment..."

            cd ~/dev/max-explorer

            echo "🔄 Pulling latest code"
            git checkout .
            git pull origin main

            echo "🐳 Building and starting Docker containers"
            export DATABASE_URL="$DATABASE_URL"
            export POSTGRES_USER="$POSTGRES_USER"
            export POSTGRES_PASSWORD="$POSTGRES_PASSWORD"
            export POSTGRES_DB="$POSTGRES_DB"
            export OPEN_WEATHER_MAP_API_KEY="$OPEN_WEATHER_MAP_API_KEY"
            export LAUNCH_CRON_ON_INIT=true

            sudo docker compose -f docker-compose.prod.yml down
            sudo docker compose -f docker-compose.prod.yml up -d --build

            echo "✅ Deployment complete! (migrations run automatically)"
